### ISSUE TITLE
Follow `XDG_*_HOME` environment variables on all platforms?

### ISSUE THREAD

**Issue by Siilwyn** [sindresorhus/env-paths#7]
Wondering if it would be a good idea to allow the user to always choose the location using the XDG variables, coming from this request: https://github.com/js-cli/js-v8flags/pull/47

**Comment by sindresorhus** [comment]
I don't really see the benefit of that. Seems like a good way for users to shoot themselves in the foot by using a directory with the wrong permissions and then go complaining about it open source projects' issue trackers. `XDG_*_HOME` exists on Linux because nothing is a hard convention there, but on macOS and Windows there are standard directories to use.

As an example, we used to use `~/.config` as default on Linux *and* macOS for config, for the Yeoman project. Through the project lifetime, this caused an endless amount of user frustration as a big percentage of users have the wrong permissions on that directory (probably other tools setting the wrong permission there…).

So, my point is, there are huge benefits to always using the system-defined directories.

**Comment by Siilwyn** [comment]
Sounds clear to me, thanks for tuning in @sindresorhus.
